### ISSUE TITLE
env.backends.onnx.logLevel = "fatal"; does not work

### ISSUE THREAD

**Issue by sroussey** [xenova/transformers.js#529]
### System Info

2.14.0 on MacOS node env

### Environment/Platform

- [ ] Website/web-app
- [ ] Browser extension
- [X] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

env.backends.onnx.logLevel = "fatal";

This does not have an effect as expected.

When creating a pipeline, in options, setting a config with {log_severity_level:4} works but breaks other things as it is not added to a config, but overwrites it.

### Reproduction

I have a nice little download progress bar but I can't see it when it floods with messages like 

```
2024-01-21 20:57:14.104 bun[74866:28886536] 2024-01-21 20:57:14.103988 [W:onnxruntime:, graph.cc:3553 CleanUnusedInitializersAndNodeArgs] Removing initializer '/decoder/block.0/layer.2/DenseReluDense/act/Constant_4_output_0'. It is not used by any node and should be removed from the model.
2024-01-21 20:57:14.104 bun[74866:28886536] 2024-01-21 20:57:14.104000 [W:onnxruntime:, graph.cc:3553 CleanUnusedInitializersAndNodeArgs] Removing initializer '/decoder/block.18/layer.2/DenseReluDense/act/Constant_2_output_0'. It is not used by any node and should be removed from the model.
2024-01-21 20:57:14.104 bun[74866:28886536] 2024-01-21 20:57:14.104009 [W:onnxruntime:, graph.cc:3553 CleanUnusedInitializersAndNodeArgs] Removing initializer '/decoder/block.13/layer.2/DenseReluDense/act/Constant_4_output_0'. It is not used by any node and should be removed from the model.
2024-01-21 20:57:14.104 bun[74866:28886536] 2024-01-21 20:57:14.104019 [W:onnxruntime:, graph.cc:3553 CleanUnusedInitializersAndNodeArgs] Removing initialize
```

**Comment by sroussey** [comment]
Just in case it is upstream: https://github.com/microsoft/onnxruntime/issues/19225

**Comment by xenova** [comment]
Hi there 👋 Yes, this is a bug with onnxruntime itself, and it has been reported before at #270. This should be fixed once we upgrade to ORT v1.17.

**Comment by sroussey** [comment]
Thanks for the update. I used the linked PR in my fork and it seems to work well enough, but looking forward to not needing a fork later. :)

**Comment by fs-eire** [comment]
Upgrading to 1.17 does not fix this problem for onnxruntime-node. I think that flag currently only works for onnxruntime-web. Need a fix.

**Comment by LostBeard** [comment]
> env.backends.onnx.logLevel = "fatal";
> This does not have an effect as expected.

Not working in Transformer.js 3.6.3 either. 

I am using Transformer.js in a web extension and I can't prevent (using Transformer.js log verbosity settings) the below messages.

```
2025-08-02 11:50:59.629399 [W:onnxruntime:, session_state.cc:1280 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
Bc @ ort-wasm-simd-threaded.jsep.mjs:100
$func11828 @ ort-wasm-simd-threaded.jsep.wasm:0xf9915f
$func1841 @ ort-wasm-simd-threaded.jsep.wasm:0x22df9c
$func810 @ ort-wasm-simd-threaded.jsep.wasm:0xb9ef0
$func11762 @ ort-wasm-simd-threaded.jsep.wasm:0xf92915
$func697 @ ort-wasm-simd-threaded.jsep.wasm:0x9f9bb
$func88 @ ort-wasm-simd-threaded.jsep.wasm:0xdb66
$func14346 @ ort-wasm-simd-threaded.jsep.wasm:0x12d4ecb
$func119 @ ort-wasm-simd-threaded.jsep.wasm:0x15503
$func1384 @ ort-wasm-simd-threaded.jsep.wasm:0x177a32
$func11276 @ ort-wasm-simd-threaded.jsep.wasm:0xf4d91f
$Ma @ ort-wasm-simd-threaded.jsep.wasm:0xae2f36
Hd.b.<computed> @ ort-wasm-simd-threaded.jsep.mjs:77
e._OrtCreateSession @ ort-wasm-simd-threaded.jsep.mjs:104
(anonymous) @ ort-wasm-simd-threaded.jsep.mjs:14
xr @ content.js:42844
await in xr
uc @ content.js:42844
loadModel @ content.js:42844
createInferenceSessionHandler @ content.js:42844
create @ content.js:40022
await in create
createInferenceSession @ content.js:3666
(anonymous) @ content.js:8421Understand this error
ort-wasm-simd-threaded.jsep.mjs:100 2025-08-02 11:50:59.630999 [W:onnxruntime:, session_state.cc:1282 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
```

**Comment by fs-eire** [comment]
the `logLevel` setting is not adjusted dynamically. it only affects when creating ONNX Runtime Env, which means once you already used any ORT APIs, the config does not take effect. you need to set it very early.

**Comment by xenova** [comment]
We finally got around to fixing this (which was made possible by a bug fix in onnxruntime) :) https://github.com/huggingface/transformers.js/pull/1507
